### ISSUE TITLE
Add Bio

### ISSUE THREAD

**Issue by Eni-G** [ipsilon/evmsummit.org#15]
https://github.com/ipsilon/evmsummit.org/blob/811a6a8db3f607ef6719be5a0e826e3a96039d9e/index.html#L298

Bio: Mamy has been an Ethereum core dev for 5 years, developing the Nimbus consensus client. After the success of The Merge, he now focuses on scaling Ethereum, by leading the ZK engineering team at Taiko.

@hugo-dc

**Comment by hugo-dc** [comment]
Updated in PR https://github.com/ipsilon/evmsummit.org/pull/16/files
