### ISSUE TITLE
Update Archive button and link

### ISSUE THREAD

**Issue by Eni-G** [ipsilon/evmsummit.org#38]
Please change the name of the button to: "Watch the Recordings"

And the link to: https://streameth.org/archive?event=evm_summit

Also, switch it with "Learn More" to make this the first button.

@hugo-dc @gumb0

https://github.com/ipsilon/evmsummit.org/blob/cb81f912ffa0cb06e320beba4376e2bfc53e6c47/index.html#L104

**Comment by hugo-dc** [comment]
PR: https://github.com/ipsilon/evmsummit.org/pull/39
