### ISSUE TITLE
Rephrase line

### ISSUE THREAD

**Issue by Eni-G** [ipsilon/evmsummit.org#43]
Rephrase the line to:
			<h2>Who are the EVM sessions at Devcon 7 SEA directed to?</h2>

https://github.com/ipsilon/evmsummit.org/blob/1409916fb8c058e8d792cebb6ce91f6868d75723/index.html#L136

**Comment by hugo-dc** [comment]
Changed here: https://github.com/ipsilon/evmsummit.org/pull/40
